spring.application.name=spring-boot-001
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.username=root
spring.datasource.password=root12
spring.datasource.url=jdbc:mysql://localhost:3306/it_shaala